name: Tesla OS Pipeline

# Esto le dice al robot que se ejecute cada vez que haga un "push" a la rama main (o master)
on:
  push:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ“¥ Clonar el cÃ³digo
      uses: actions/checkout@v3

    - name: âš™ï¸ Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: ğŸ“¦ Instalar dependencias
      run: npm install

    - name: ğŸ§ª Ejecutar Pruebas Unitarias (Jest)
      env:
        #  GitHub inyecta los secretos que guarde en la configuraciÃ³n
        MONGO_URI: ${{ secrets.MONGO_URI }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: npm test